### PR TITLE
NPI-3458 implement solution types utility classes

### PR DESCRIPTION
**Pull request by treefern**
This PR adds utility classes to more formally capture the definitions of solution types defined by IGS. This avoids identifying solution types by short strings throughout the codebase, and allows additional details of each solution type to potentially be captured here as well.

### CODE REVIEW

**Review by ronaldmaj — COMMENTED** [review]
This looks good to me, adds new code but doesn't alter anything existing so won't cause issues. Plus this will help heaps in our Ops space in making things clearer. 

The one thing that could be added are unit tests on these methods, but if this needs to be in the repo to help with testing on Ops, happy for this to go in sooner

**Review by ronaldmaj — APPROVED** [review]
Looks good to me, thanks for putting this together! I tested the ability to change the name string after instantiating it and I'm getting the `AttributeError`, so all seems to be working :+1:

**Comment by treefern** [comment]
Updated to more robustly work as static classes, preventing modification of class variables. Some other tidying. Addition of unit tests.
This should be ready to go in now.

**Review by ronaldmaj — APPROVED** [review]
Awesome, thanks for putting in the unit tests as well, this will make this a lot more robust to chances in future. Happy for this to go in :+1:

**Pull request merged**
